version: '3.8'

services:
  api:
    build:
      context: ./API
      dockerfile: API.Application/Dockerfile
    ports:
      - "4201:4201"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4201
      - API_TITLE=AI Cookbook API
      - API_VERSION=v1
      - API_DESCRIPTION=A minimal API for the AI Cookbook project
      - API_CONTACT_NAME=AI Cookbook Team
      - API_CONTACT_EMAIL=contact@aicookbook.com
      - CORS_ALLOWED_ORIGINS=http://localhost:4200,http://localhost:3000,http://localhost:8080
      - CORS_ALLOWED_METHODS=GET,POST,PUT,DELETE,OPTIONS
      - CORS_ALLOWED_HEADERS=*
      - SWAGGER_ENABLED=true
      - SWAGGER_ROUTE_PREFIX=
      - SWAGGER_DOCUMENT_TITLE=AI Cookbook API Documentation
      - RECIPES_PATH=recipes
      - COSMOSDB_DATABASE_NAME=CookBook
      - COSMOSDB_CONTAINER_NAME=Recipes
      - COSMOSDB_WEEK_MENU_CONTAINER_NAME=WeekMenu
      - COSMOSDB_COOKBOOK_CONTAINER_NAME=Cookbooks
      - COSMOSDB_GROCERY_LIST_CONTAINER_NAME=GroceryLists
      - COSMOSDB_PARTITION_KEY_PATH=/id
      - COSMOSDB_THROUGHPUT=400
      - COSMOSDB_CREATE_IF_NOT_EXISTS=true
      - COSMOSDB_CONNECTION_STRING=${COSMOSDB_CONNECTION_STRING}
    networks:
      - ai-cookbook-network

  web:
    build:
      context: ./Web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - ai-cookbook-network

networks:
  ai-cookbook-network:
    driver: bridge
