apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: ai-cookbook
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: ai-cookbook-api:latest
        imagePullPolicy: Never  # Use local image for development
        ports:
        - containerPort: 4201
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ASPNETCORE_URLS
          value: "http://+:4201"
        envFrom:
        - configMapRef:
            name: ai-cookbook-config
        - secretRef:
            name: ai-cookbook-secrets
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
