apiVersion: v1
kind: Service
metadata:
  name: api-external-service
  namespace: ai-cookbook
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - name: http
    port: 4201
    targetPort: 4201
    protocol: TCP
  type: LoadBalancer
