apiVersion: v1
kind: Secret
metadata:
  name: ai-cookbook-secrets
  namespace: ai-cookbook
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  # To encode: echo -n "your-value" | base64
  COSMOSDB_CONNECTION_STRING: "QWNjb3VudEVuZHBvaW50PWh0dHBzOi8vY29zbW9zLWFpLWNvb2tib29rLmRvY3VtZW50cy5henVyZS5jb206NDQzLztBY2NvdW50S2V5PTA3ZXRhR05TVW8zU0VKUTBPYnFNM0dxRXAzN1l0VUlwbXBGaEZPU3BuYnZQZnpmYndmNDdtWVdZbmp5MkNPeHpVTXh1NUEwbHlxcFBBQ0RiRm9PcDF3PT0="
