# AI-Cookbook Configuration Map
# This file contains all application configuration that can be updated without rebuilding images
apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-cookbook-config
  namespace: ai-cookbook
  labels:
    app.kubernetes.io/name: ai-cookbook
    app.kubernetes.io/part-of: ai-cookbook
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: config
  annotations:
    config.kubernetes.io/local-config: "true"
    description: "AI Cookbook application configuration"
    last-updated: "2024-01-01T00:00:00Z"
data:
  # API Configuration
  API_TITLE: "AI Cookbook API"
  API_VERSION: "v1"
  API_DESCRIPTION: "A minimal API for the AI Cookbook project"
  API_CONTACT_NAME: "AI Cookbook Team"
  API_CONTACT_EMAIL: "contact@aicookbook.com"
  
  # CORS Configuration - More restrictive headers
  CORS_ALLOWED_ORIGINS: "http://localhost:4200,http://localhost:3000,http://localhost:8080"
  CORS_ALLOWED_METHODS: "GET,POST,PUT,DELETE,OPTIONS"
  CORS_ALLOWED_HEADERS: "Content-Type,Authorization,X-Requested-With,Accept,Origin"
  CORS_ALLOW_CREDENTIALS: "true"
  CORS_MAX_AGE: "3600"
  
  # Swagger Configuration
  SWAGGER_ENABLED: "true"
  SWAGGER_ROUTE_PREFIX: ""
  SWAGGER_DOCUMENT_TITLE: "AI Cookbook API Documentation"
  
  # Recipes Configuration
  RECIPES_PATH: "recipes"
  
  # CosmosDB Configuration
  COSMOSDB_DATABASE_NAME: "CookBook"
  COSMOSDB_CONTAINER_NAME: "Recipes"
  COSMOSDB_WEEK_MENU_CONTAINER_NAME: "WeekMenu"
  COSMOSDB_COOKBOOK_CONTAINER_NAME: "Cookbooks"
  COSMOSDB_GROCERY_LIST_CONTAINER_NAME: "GroceryLists"
  COSMOSDB_PARTITION_KEY_PATH: "/id"
  COSMOSDB_THROUGHPUT: "400"
  COSMOSDB_CREATE_IF_NOT_EXISTS: "true"
  
  # Health Check Configuration
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_INTERVAL: "30s"
  
  # Logging Configuration
  LOG_LEVEL: "Information"
  LOG_FORMAT: "json"
  
  # Performance Configuration
  MAX_REQUEST_SIZE: "10485760"  # 10MB
  REQUEST_TIMEOUT: "60"
  
  # Cache Configuration
  CACHE_ENABLED: "true"
  CACHE_TTL: "300"  # 5 minutes
  
  # Rate Limiting Configuration
  RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_REQUESTS_PER_MINUTE: "100"
  RATE_LIMIT_BURST: "20"