apiVersion: v1
kind: Secret
metadata:
  name: ai-cookbook-tls
  namespace: ai-cookbook
  labels:
    app.kubernetes.io/name: ai-cookbook
    app.kubernetes.io/part-of: ai-cookbook
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: kubectl
    app.kubernetes.io/component: tls
  annotations:
    description: "TLS certificate for AI Cookbook ingress"
type: kubernetes.io/tls
data:
  # Replace with your actual base64 encoded certificate and key
  # To generate: kubectl create secret tls ai-cookbook-tls --cert=path/to/cert.pem --key=path/to/key.pem --dry-run=client -o yaml
  tls.crt: ""  # Base64 encoded certificate
  tls.key: ""  # Base64 encoded private key
